FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VideoLingua

### Get Dictionary data (dictionary) [/video/{video}] [POST]

+ Request (application/json)

        {
            "youtube_video_id": "PknlyXsPY2E",
            "start_time": "00:00:00",
            "end_time" : "00:05:15",
            "topic_id": 1,
            "type_id": 2,
            "video_cut_off" : 0, 
            "title": "Chemical Reactions",
            "description": "Advanced Chemistry lection",
            "difficulty_id": 1,
            "dialect_id": 2
        }

+ Response 200 (application/json)

      "videos":[  
      {  
         "id":1,
         "youtube_video_id":"PknlyXsPY2E",
         "start_time":"00:00:00",
         "end_time":"00:00:00",
         "video_cut_off":0,
         "title":"News Summary - 1 PM 03\/01\/2016",
         "difficulty_id":1,
         "topic_id":0,
         "type_id":0,
         "dialect_id":1,
         "status_id":2,
         "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis dui risus. Donec tempor mollis arcu eu semper. In lectus ante, faucibus sed dolor eu, placerat porttitor dolor.",
         "created_at":null,
         "updated_at":"2017-08-12 18:16:33",
         "status":{  
            "id":2,
            "title":"published"
         },
         "topic":null,
         "type":null,
         "difficulty":{  
            "id":1,
            "title":"Novice"
         },
         "dialect":{  
            "id":1,
            "title":"Levantine"
         },
         "subtitles":[  
            {  
               "id":265,
               "video_id":1,
               "dialect":null,
               "start_time":"00:00:00",
               "end_time":"00:00:05",
               "msa":null,
               "english":null,
               "transliteration":null,
               "created_at":"2017-09-21 17:22:42",
               "updated_at":"2017-09-22 06:23:44",
               "dictionary": {
                    id:1,
                    subtitleId: 265,
                    phrases: [
                    {
                     id:1,
                     substring: 'I like apples',
                     coords: [
                         {start: 0, end: 6}, //I like
                         {start: 14, end: 20} //apples
                     ],
                     translation: 'Jaime les pommes',
                     metadata: 'plural sing.'
                    },
                }  
            },
            {  
               "id":278,
               "video_id":1,
               "dialect":null,
               "start_time":"00:00:00",
               "end_time":"00:00:10",
               "msa":null,
               "english":null,
               "transliteration":null,
               "created_at":"2017-09-22 06:25:41",
               "updated_at":"2017-09-22 06:25:41",
               "dictionary": {
                    id:2,
                    subtitleId: 278,
                    phrases: [
                    {
                     id:1,
                     substring: 'I like apples',
                     coords: [
                         {start: 0, end: 6}, //I like
                         {start: 14, end: 20} //apples
                     ],
                     translation: 'Jaime les pommes',
                     metadata: 'plural sing.'
                    },
                }  
            }
         ],

      },]
      
      
